#pragma once

#define VERTEX_QUANTITY 13

#define MAX_TAXICARS 20
#define TAXICAR_IMG_HEIGHT 32
#define TAXICAR_IMG_WIDTH 32
#define SPEED _maxVelocity / 30

#define PASSENGER_OFFSET 35
#define PASSENGER_HEIGHT 16

#define ANTISPAM_INTERVAL 500